spring:
  profiles: default
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: default-eureka-server.com
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: peer-1
  application:
    name: eureka-server-clustered
server:
  port: 8761
eureka:
  instance:
    hostname: peer-1-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-2-server.com:8762/eureka/

---
spring:
  profiles: peer-2
  application:
    name: eureka-server-clustered
server:
  port: 8762
eureka:
  instance:
    hostname: peer-2-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-1-server.com:8761/eureka/
