server:
  port: 8761
eureka:
  instance:
    hostname: eureka.mayex.org
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1.mayex.org:${server.port}/eureka/, http://eureka2.mayex.org:${server.port}/eureka/