---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: default-eureka-server.com
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: peer-1
  application:
    name: eureka-server-clustered
server:
  port: 8761
eureka:
  instance:
    hostname: peer-1-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-2-server.com:8762/eureka/,http://peer-3-server.com:8763/eureka/

---
spring:
  profiles: peer-2
  application:
    name: eureka-server-clustered
server:
  port: 8762
eureka:
  instance:
    hostname: peer-2-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-1-server.com:8761/eureka/,http://peer-3-server.com:8763/eureka/

---
spring:
  profiles: peer-3
  application:
    name: eureka-server-clustered
server:
  port: 8763
eureka:
  instance:
    hostname: peer-3-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-1-server.com:8761/eureka/,http://peer-2-server.com:8762/eureka/